- purl: pkg:deb/ubuntu/grafana@2.6.0%2Bdfsg-1?arch=source&distro=xenial
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-1000816
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-12099
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-15727
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-18623
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-18624
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-18625
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-19039
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-31123
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-35957
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-36062
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-39201
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-39307
  fixing_advisories: []
