- purl: pkg:deb/ubuntu/ansible@2.0.0.2-2ubuntu1?arch=source&distro=esm-apps/xenial
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-2568
  fixing_advisories: []
- purl: pkg:deb/ubuntu/ansible@2.0.0.2-2ubuntu1?arch=source&distro=xenial
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-10875
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-16837
  fixing_advisories: []
