- purl: pkg:deb/ubuntu/kubernetes@1.0?arch=source&distro=jammy
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-1002100
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-1002102
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-1002105
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-24829
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-3162
  fixing_advisories: []
- purl: pkg:deb/ubuntu/kubernetes@1.0?arch=source&distro=noble
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-1002100
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-1002102
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-1002105
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-24829
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-3162
  fixing_advisories: []
- purl: pkg:deb/ubuntu/kubernetes@1.0?arch=source&distro=esm-apps/focal
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-1002100
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-1002102
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-1002105
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-24829
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-3162
  fixing_advisories: []
