- purl: pkg:deb/ubuntu/ansible@2.5.1%2Bdfsg-1ubuntu0.1?arch=source&distro=bionic
  affected_by_advisories: []
  fixing_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-10855
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-10874
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-10875
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-16837
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-16876
- purl: pkg:deb/ubuntu/ansible@2.5.1%2Bdfsg-1ubuntu0.1?arch=source&distro=esm-apps/bionic
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-2568
  fixing_advisories: []
