- purl: pkg:deb/ubuntu/ansible@1.4.3%2Bdfsg-1?arch=source&distro=esm-infra-legacy/trusty
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-16837
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-2568
  fixing_advisories: []
