- purl: pkg:deb/ubuntu/ansible@2.10.7%2Bmerged%2Bbase%2B2.10.8%2Bdfsg-1ubuntu0.1~esm4?arch=source&distro=esm-apps/jammy
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-2568
  fixing_advisories: []
